### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by WinkelmeierTestRepo** [AlexanderWinkelmeier/github-crash-course#1]
I think it looks better when the main title is a bit more orange.

```css
h1 {
  color: #ed9a0a;
}
```
